### ISSUE TITLE
Create builder for SLC6 + devtoolset3

### ISSUE THREAD

**Issue by ktf** [alisw/docks#94]
See also alisw/alidist#284 .

**Comment by dberzano** [comment]
This is needed for:

* Making AliceO2 work with devtoolset
* Making AliRoot work with RPM-installed AMORE
* Having continuous integration for DA RPMs

The idea is that the container should match the environment of DAQ nodes (which have devtoolset).

Proposed container name: `alisw/slc6-daq-builder`.

**Comment by dberzano** [comment]
@Barthelemy for your information.

**Comment by dberzano** [comment]
We don't need a special container for this, see alisw/alidist#438 and alisw/ali-bot#264.

**Comment by ktf** [comment]
Actually @Barthelemy wanted this for O2 as well. Is that use case covered as well?
